// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHealth) DeepCopyInto(out *PodHealth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHealth.
func (in *PodHealth) DeepCopy() *PodHealth {
	if in == nil {
		return nil
	}
	out := new(PodHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodHealth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHealthList) DeepCopyInto(out *PodHealthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodHealth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHealthList.
func (in *PodHealthList) DeepCopy() *PodHealthList {
	if in == nil {
		return nil
	}
	out := new(PodHealthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodHealthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHealthSpec) DeepCopyInto(out *PodHealthSpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHealthSpec.
func (in *PodHealthSpec) DeepCopy() *PodHealthSpec {
	if in == nil {
		return nil
	}
	out := new(PodHealthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHealthStatus) DeepCopyInto(out *PodHealthStatus) {
	*out = *in
	in.LastChecked.DeepCopyInto(&out.LastChecked)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHealthStatus.
func (in *PodHealthStatus) DeepCopy() *PodHealthStatus {
	if in == nil {
		return nil
	}
	out := new(PodHealthStatus)
	in.DeepCopyInto(out)
	return out
}
